// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Date
}

type User struct {
	ID   int32
	Name string
	Age  int32
}
