// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const deleteUserByName = `-- name: DeleteUserByName :exec
DELETE FROM users
WHERE name = $1
`

func (q *Queries) DeleteUserByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteUserByName, name)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, age
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (*User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return &i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, age
FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return &i, err
}
